require "werewolf/version"
require "werewolf/slackbot"
require "werewolf/game"
require "werewolf/player"
require "werewolf/commands/join"
require "werewolf/commands/start"
require "werewolf/commands/status"
require "werewolf/commands/vote"
